### ISSUE TITLE
Kafka Bridge REST API always returns 404, even for /healthy and /ready

### ISSUE THREAD

**Issue by jonganej** [strimzi/strimzi-kafka-bridge#344]
I configured a Kafka bridge as follows:
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaBridge
metadata:
  name: kafka-bridge-pilot
spec:
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  authentication:
    type: scram-sha-512
    username: kafka-bridge-user
    passwordSecret:
      secretName: kafka-bridge-user
      password: password
  tls:
    trustedCertificates:
    - secretName: my-cluster-cluster-ca-cert
      certificate: ca.crt
  jvmOptions:
    gcLoggingEnabled: false
  http:
    port: 8080
```
with the `kafka-bridge-user` `KafkaUser` belonging to a particular consumer group and being able to read / write from certain topics and even 'read from the cluster', whatever that entails.

Upon starting up Kafka Bridge, I receive a single `io.vertx.core.VertxException: Thread blocked` exception and then finally
```
2019-09-19 15:05:14,948 INFO HTTP-Kafka Bridge started and listening on port 8080 (io.strimzi.kafka.bridge.http.HttpBridge) [vert.x-eventloop-thread-1]
```
implying that the bridge should be working fine.

However, any API call, even `/healthy` and `/ready` returns a 404 with this log:
```
2019-09-19 15:05:40,027 INFO [731249391] Response: statusCode = 404, message = Not Found (io.strimzi.kafka.bridge.http.HttpUtils) [vert.x-eventloop-thread-1]
```

Does anyone know what's the reason for this? I doubt it's a `KafkaUser` authorization issue. And even if it were a configuration issue on the Bridge side, the logs appear deceptively okay.
