### ISSUE TITLE
Kafka Bridge not working as expected with 2 replicas

### ISSUE THREAD

**Issue by shalin-hudda** [strimzi/strimzi-kafka-bridge#498]
I want to have at least 2 replicas of Kafka Bridge to build in some redundancy in case of failure. Therefore, I am using the following yml with 2 replicas.
```yml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaBridge
metadata:
  name: my-bridge
  namespace: test
spec:
  authentication:
    type: tls
    certificateAndKey:
      secretName: my-user
      certificate: user.crt
      key: user.key
  tls:
    trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        certificate: ca.crt
  bootstrapServers: 'my-cluster-kafka-bootstrap:9093'
  consumer:
    config:
      auto.offset.reset: earliest
      enable.auto.commit: true
  http:
    port: 8080
  producer:
    config:
      acks: 1
      delivery.timeout.ms: 300000
  replicas: 2
```
However, when the HTTP consumer tries to fetch records using the polling mechanism, the 1st replica responds as expected with the message but the 2nd replica responds with message not found and a 404 error response. 

Following is my topic yaml
```yml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: topic-1
  namespace: test
  labels:
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: topic-1
spec:
  partitions: 1
  replicas: 1
```

Is this an expected response? Why is this happening?
