### ISSUE TITLE
Kafka-Bridge access via Ingress

### ISSUE THREAD

**Issue by Leviathan321** [strimzi/strimzi-kafka-bridge#538]
In my setup the strimzi kafka bridge is running, but I have problems accessing the <deployhostname>/healthy or any other endpoints.
Kafka-bridge service is called "kafka-bridge" and it is running on the 8080 port.
I am using the following Ingress configuration:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-controller
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: kafka.192.168.42.129.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kafka-bridge-bridge-service
            port: 
              number: 8080
```
When I remove the ssl-redirect annotation I get a redirect from Ingress, and I am able to acces the cluster with the service IP (10.1.243.219), but now via "kafka.192.168.42.129.nip.io".
```
curl -X POST http://10.1.243.219:8080/consumers/my-group   -H 'content-type: application/vnd.kafka.v2+json'   -d '{
    "name": "mrm",
    "format": "json",
    "auto.offset.reset": "earliest",
    "enable.auto.commit": false
  }'
{"instance_id":"mrm","base_uri":"http://10.1.243.219:8080/consumers/my-group/instances/mrm"}
```

When I check the ingress configuration, the endpoint is also said to not exist:

```
$ microk8s kubectl describe ingress

Name:             ingress-controller
Namespace:        default
Address:          127.0.0.1
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  ingress-tls terminates keycloak.192.168.42.129.nip.io,sb.192.168.42.129.nip.io,mrm.192.168.42.129.nip.io
Rules:
  Host                            Path  Backends
  ----                            ----  --------
  keycloak.192.168.42.129.nip.io  
                                  /   keycloak:8081 (<error: endpoints "keycloak" not found>)
  sb.192.168.42.129.nip.io        
                                  /   web:5000 (<none>)
  mrm.192.168.42.129.nip.io       
                                  /   mrm:8080 (<none>)
  kafka.192.168.42.129.nip.io     
                                  /   kafka-bridge-bridge-service:8080 (<error: endpoints "kafka-bridge-bridge-service" not found>)
Annotations:                      kubernetes.io/ingress.class: public
Events:
  Type    Reason  Age    From                      Message
  ----    ------  ----   ----                      -------
  Normal  CREATE  4m38s  nginx-ingress-controller  Ingress default/ingress-controller
  Normal  UPDATE  4m2s   nginx-ingress-controller  Ingress default/ingress-controller
```
