### ISSUE TITLE
JVM options provided by the Strimzi cluster operator are ignored

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#571]
When the bridge is deployed through the Strimzi by specifying the `spec.jvmOptions` as well only the `gcLoggingEnabled` is taken into account, while the others are all just ignored.
For example, using something like the following:

```yaml
  jvmOptions:
    "-Xmx": "1g"
    "-Xms": "1g"
    javaSystemProperties:
    - name: javax.net.debug
      value: ssl
```

Will result in the bridge not starting by using the above heap sizing and corresponding system properties; they will be just ignored.
