### ISSUE TITLE
Enabling metrics for a custom deployment of the bridge

### ISSUE THREAD

**Issue by Anthuang** [strimzi/strimzi-kafka-bridge#641]
Hey again,

We're trying to set up Prometheus to scrape the bridge, but it doesn't seem like Prometheus is getting any metrics. I currently have a local set up to try to do this. This local setup is essentially how we're running it live--we run the bridge image directly without using the Strimzi CRD.

Bridge started with:

```
$ bin/kafka_bridge_run.sh --config config/application.properties
```

Relevant application.properties:

```
http.host=0.0.0.0
http.port=9999
```

Prometheus started with:

```
./prometheus --config.file=prometheus.yml
```

prometheus.yml:

```yaml
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      # Implicitly scrapes /metrics
      - targets: ["localhost:9999"]
```

I'm assuming that https://github.com/strimzi/strimzi-kafka-bridge/blob/main/src/main/resources/jmx_metrics_config.yaml is the JMX exporter config that gets used. I don't see these metrics on Prometheus.

I was wondering if there's additional setup required? Not sure how this https://github.com/strimzi/strimzi-kafka-operator/blob/fa6289c0fb7eedd389d5922e75bdbae0c5b3085d/packaging/examples/metrics/kafka-bridge-metrics.yaml#L10 gets passed to the bridge, but maybe I'm missing that?
