### ISSUE TITLE
Latency alerts

### ISSUE THREAD

**Issue by mkl262** [strimzi/strimzi-kafka-bridge#916]
Hello,

I use Bridge only as a producer in my system, And connect it to AWS MSK as a backend.
I am occasionally getting alerts for high consumer fetch latency (based on strimzi_bridge_kafka_producer_request_latency_avg metric). What is the meaning of this alert? how can I resolve it?

bridge config:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: bridge
  namespace: kafka
spec:
  replicas: 2
  bootstrapServers: "b-1.<clusterID>.kafka.<region>.amazonaws.com:9092,b-2.<clusterID>.kafka.<region>.amazonaws.com:9092,b-3.<clusterID>.kafka.<region>.amazonaws.com:9092"
  http:
    port: 8080
  enableMetrics: true
  template:
    pod:
      metadata:
        annotations:
          prometheus.io/scrape: 'true'
          prometheus.io/port: '8080'
```

Grafana screenshot:
<img width="1496" alt="Screenshot 2024-07-06 at 0 38 07" src="https://github.com/strimzi/strimzi-kafka-bridge/assets/8472607/f5c3e9ee-80df-450d-b366-8acbbca88d47">
